//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyKeHoachHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCNKhoa
    {
        public int ID { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public string TenBCN { get; set; }
    }
}
