//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyKeHoachHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHHT()
        {
            this.ThongKes = new HashSet<ThongKe>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_MH { get; set; }
        public Nullable<int> ID_HK { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> NutTick { get; set; }
    
        public virtual HocKi HocKi { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKe> ThongKes { get; set; }
    }
}
