//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyKeHoachHocTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEP_TEAM15_DKKKHHTEntities : DbContext
    {
        public SEP_TEAM15_DKKKHHTEntities()
            : base("name=SEP_TEAM15_DKKKHHTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BCNKhoa> BCNKhoas { get; set; }
        public virtual DbSet<HocKi> HocKis { get; set; }
        public virtual DbSet<KHHT> KHHTs { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongKe> ThongKes { get; set; }
    }
}
